// benchmarks/news/vue-vapor/src/hydration-interactivity/App.vue
<script setup vapor lang="ts">
import { shallowRef } from 'vue';
import { CARDS, INITIAL_VALUE } from '../../../../hydration-interactivity/shared.js';

const props = defineProps<{
	controlled?: boolean;
	deferred?: boolean;
}>();

const draft = shallowRef(INITIAL_VALUE);
const clicks = shallowRef(0);

function onInput(event: Event) {
	draft.value = (event.currentTarget as HTMLInputElement).value;
}
</script>

<template>
	<main class="hydration-page">
		<h1>Hydration interactivity benchmark</h1>
		<section class="hydration-editor">
			<label for="hydration-input">Your draft</label>
			<input
				v-if="props.controlled"
				id="hydration-input"
				autocomplete="off"
				:value="draft"
				@input="onInput"
			/>
			<input v-else id="hydration-input" autocomplete="off" @input="onInput" />
			<output id="hydration-output">{{ draft }}</output>
			<button id="hydration-action" type="button" @click="clicks++">Record interaction</button>
			<output id="hydration-clicks">{{ clicks }}</output>
		</section>
		<ul id="hydration-cards">
			<li v-for="card of CARDS" :key="card.id" class="hydration-card" :data-card-id="card.id">
				<h2>{{ card.title }}</h2>
				<p>{{ card.description }}</p>
			</li>
		</ul>
	</main>
</template>

// benchmarks/news/react/src/hydration-interactivity/App.tsx
import { useState, type FormEvent } from 'react';
import { CARDS, INITIAL_VALUE } from '../../../../hydration-interactivity/shared.js';

type HydrationBenchmarkProps = {
	controlled?: boolean;
	deferred?: boolean;
};

export function App({ controlled = false }: HydrationBenchmarkProps) {
	const [draft, setDraft] = useState(INITIAL_VALUE);
	const [clicks, setClicks] = useState(0);
	const onInput = (event: FormEvent<HTMLInputElement>) => setDraft(event.currentTarget.value);

	return (
		<main className="hydration-page">
			<h1>Hydration interactivity benchmark</h1>
			<section className="hydration-editor">
				<label htmlFor="hydration-input">Your draft</label>
				{controlled ? (
					<input id="hydration-input" autoComplete="off" value={draft} onInput={onInput} />
				) : (
					<input id="hydration-input" autoComplete="off" onInput={onInput} />
				)}
				<output id="hydration-output">{draft}</output>
				<button id="hydration-action" type="button" onClick={() => setClicks(clicks + 1)}>
					Record interaction
				</button>
				<output id="hydration-clicks">{clicks}</output>
			</section>
			<ul id="hydration-cards">
				{CARDS.map((card) => (
					<li className="hydration-card" data-card-id={card.id} key={card.id}>
						<h2>{card.title}</h2>
						<p>{card.description}</p>
					</li>
				))}
			</ul>
		</main>
	);
}
